#!/usr/bin/env bash
# =============================================================================
# gen_coverage_exclude.sh  NCL NC NW NT  ->  emits a CONFIG-SPECIFIC Questa
# coverage-exclusion .do on stdout.
#
# Replaces the hand-maintained pair (coverage_exclude.do + coverage_exclude_2CL.do)
# with ONE generator that scales to ANY topology N_CLUSTERS / N_CORES / N_WARPS /
# N_THREADS. merge_coverage.sh calls it with the run's config so each config's
# report only counts coverage that is actually REACHABLE for that config.
#
# PRINCIPLE (do not violate — this is the whole point of the file):
#   Only STRUCTURALLY-DEAD coverage is excluded, and every waiver is KEYED to the
#   config that makes it dead. We NEVER exclude logic that is reachable-but-merely-
#   untested (that would inflate the number dishonestly). Reachable gaps are closed
#   with directed tests instead (e.g. vote_shfl for ALU_TYPE_OTHER), not waived.
#
# Waiver classes (the '# --- Xxx:' comments are the audit label; Questa's built-in
# -reason code is in parentheses — Questa rejects custom reason strings):
#   EOTH  third-party IP, not the Vortex DUT     (cvfpu, Berkeley HardFloat in TCU)   -> EOTH
#   EUR   config-dead tied-off interface          (L2/L3 PASSTHRU cache-side buses)    -> EUR
#   ECFG  topology-structural dead condition      (e.g. global barrier at 1 core)      -> EUR
#
# Usage:
#   scripts/gen_coverage_exclude.sh 1 1 4 4 > /tmp/excl.do
#   vsim -viewcov raw.ucdb -c -do "do /tmp/excl.do; coverage save merged.ucdb; quit -f"
#
# Verify it all matched (0 stale lines):
#   grep -c "had no effect" <dryrun.log>   # expect 0
# =============================================================================
set -euo pipefail

NCL="${1:?need NUM_CLUSTERS}"
NC="${2:?need NUM_CORES}"
NW="${3:?need NUM_WARPS}"
NT="${4:?need NUM_THREADS}"

RTL="/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl"
TOP="/vortex_tb_top/dut/vortex"

# Socket layout mirrors VX_config.vh: SOCKET_SIZE = min(4, NUM_CORES);
# NUM_SOCKETS = ceil(NUM_CORES / SOCKET_SIZE).
SOCKET_SIZE=$(( NC < 4 ? NC : 4 ))
(( SOCKET_SIZE < 1 )) && SOCKET_SIZE=1
TOTAL_CORES=$(( NCL * NC ))

core_scope() {   # $1=cluster $2=core-index-within-cluster  ->  full core scope path
  local cl=$1 co=$2
  local sk=$(( co / SOCKET_SIZE ))
  local cis=$(( co % SOCKET_SIZE ))
  echo "${TOP}/g_clusters[${cl}]/cluster/g_sockets[${sk}]/socket/g_cores[${cis}]/core"
}

echo "# ============================================================================="
echo "# AUTO-GENERATED by gen_coverage_exclude.sh for config ${NCL}CL/${NC}C/${NW}W/${NT}T"
echo "# (TOTAL_CORES=${TOTAL_CORES}, SOCKET_SIZE=${SOCKET_SIZE}). Do not edit by hand."
echo "# ============================================================================="
echo

# -----------------------------------------------------------------------------
# 1. EOTH — third-party IP by DESIGN UNIT (config-independent; module names).
#    cvfpu FP core + div/sqrt + common-cells, and the Vortex cvfpu wrapper.
# -----------------------------------------------------------------------------
echo "# --- EOTH: third-party cvfpu IP (by design unit) ---"
echo "coverage exclude -du {fpnew_*}   -reason EOTH"
echo "coverage exclude -du {*mvp*}     -reason EOTH"
echo "coverage exclude -du cf_math_pkg -reason EOTH"
echo "coverage exclude -du lzc         -reason EOTH"
echo "coverage exclude -du rr_arb_tree -reason EOTH"
echo "coverage exclude -du VX_fpu_fpnew -reason EOTH"
echo "# TCU Vortex control units (Berkeley HardFloat submodules caught by scope below)"
echo "coverage exclude -du {VX_tcu_*}  -reason EOTH"
echo

# -----------------------------------------------------------------------------
# 2. EOTH — TCU FP datapath scope, per CORE instance (Berkeley HardFloat IP:
#    fNToRecFN/recFNToFN/addRecFN/... named modules that -du {VX_tcu_*} misses).
#    Enumerated over the real topology so it scales to any NCL/NC.
# -----------------------------------------------------------------------------
echo "# --- EOTH: TCU HardFloat datapath (per core) ---"
for (( cl=0; cl<NCL; cl++ )); do
  for (( co=0; co<NC; co++ )); do
    echo "coverage exclude -scope {$(core_scope $cl $co)/execute/tcu_unit} -recursive -reason EOTH"
  done
done
echo

# -----------------------------------------------------------------------------
# 3. EUR — config-dead cache-hierarchy interfaces. L2 (per cluster) and L3
#    (per GPU) are instantiated PASSTHRU (L2_ENABLE/L3_ENABLE undefined =>
#    VX_cache_cluster .PASSTHRU(1)); the cache-side bus nets are tied off and
#    never toggle. Surgically drop ONLY the dead if[0] buses (NOT the whole
#    l2/l3 scope — the passthru mux path IS exercised and must keep its hits).
# -----------------------------------------------------------------------------
echo "# --- EUR: L3 passthru dead cache interfaces (per GPU) ---"
echo "coverage exclude -scope {${TOP}/l3cache/core_bus_cache_if[0]} -recursive -reason EUR"
echo "coverage exclude -scope {${TOP}/l3cache/mem_bus_cache_if[0]}  -recursive -reason EUR"
echo
echo "# --- EUR: L2 passthru dead cache interfaces (per cluster) ---"
for (( cl=0; cl<NCL; cl++ )); do
  echo "coverage exclude -scope {${TOP}/g_clusters[${cl}]/cluster/l2cache/core_bus_cache_if[0]} -recursive -reason EUR"
  echo "coverage exclude -scope {${TOP}/g_clusters[${cl}]/cluster/l2cache/mem_bus_cache_if[0]}  -recursive -reason EUR"
done
echo

# -----------------------------------------------------------------------------
# 4. ECFG — topology-structural DEAD CONDITIONS, keyed to the config.
#
#    (a) Global barrier (VX_schedule.sv:168 `~barrier.is_global && ...`): a global
#        barrier synchronizes across ALL cores of the GPU. With a SINGLE core
#        (TOTAL_CORES==1) the runtime never issues one, so `is_global` is stuck at 0
#        and the condition can never reach its 2nd input term. Structurally dead at
#        1 core; REACHABLE at >=2 cores -> emitted ONLY when TOTAL_CORES==1.
#        (`-code c` drops the condition only; the statement/branch keep their hits.)
# -----------------------------------------------------------------------------
if (( TOTAL_CORES == 1 )); then
  echo "# --- ECFG: single-core -> global-barrier condition is structurally dead ---"
  echo "coverage exclude -srcfile ${RTL}/core/VX_schedule.sv -linerange 168 -code c -reason EUR"
  echo
else
  echo "# --- ECFG: TOTAL_CORES=${TOTAL_CORES} (>1) -> global-barrier condition is REACHABLE, NOT excluded ---"
  echo
fi

echo "# --- end generated exclusions (config ${NCL}CL/${NC}C/${NW}W/${NT}T) ---"
