# =============================================================================
# AUTO-GENERATED by gen_coverage_exclude.sh for config 2CL/2C/4W/4T
# (TOTAL_CORES=4, SOCKET_SIZE=2). Do not edit by hand.
# =============================================================================

# --- EOTH: third-party cvfpu IP (by design unit) ---
coverage exclude -du {fpnew_*}   -reason EOTH
coverage exclude -du {*mvp*}     -reason EOTH
coverage exclude -du cf_math_pkg -reason EOTH
coverage exclude -du lzc         -reason EOTH
coverage exclude -du rr_arb_tree -reason EOTH
coverage exclude -du VX_fpu_fpnew -reason EOTH
# TCU Vortex control units (Berkeley HardFloat submodules caught by scope below)
coverage exclude -du {VX_tcu_*}  -reason EOTH

# --- EOTH: TCU HardFloat datapath (per core) ---
coverage exclude -scope {/vortex_tb_top/dut/vortex/g_clusters[0]/cluster/g_sockets[0]/socket/g_cores[0]/core/execute/tcu_unit} -recursive -reason EOTH
coverage exclude -scope {/vortex_tb_top/dut/vortex/g_clusters[0]/cluster/g_sockets[0]/socket/g_cores[1]/core/execute/tcu_unit} -recursive -reason EOTH
coverage exclude -scope {/vortex_tb_top/dut/vortex/g_clusters[1]/cluster/g_sockets[0]/socket/g_cores[0]/core/execute/tcu_unit} -recursive -reason EOTH
coverage exclude -scope {/vortex_tb_top/dut/vortex/g_clusters[1]/cluster/g_sockets[0]/socket/g_cores[1]/core/execute/tcu_unit} -recursive -reason EOTH

# --- EUR: L3 passthru dead cache interfaces (per GPU) ---
coverage exclude -scope {/vortex_tb_top/dut/vortex/l3cache/core_bus_cache_if[0]} -recursive -reason EUR
coverage exclude -scope {/vortex_tb_top/dut/vortex/l3cache/mem_bus_cache_if[0]}  -recursive -reason EUR

# --- EUR: L2 passthru dead cache interfaces (per cluster) ---
coverage exclude -scope {/vortex_tb_top/dut/vortex/g_clusters[0]/cluster/l2cache/core_bus_cache_if[0]} -recursive -reason EUR
coverage exclude -scope {/vortex_tb_top/dut/vortex/g_clusters[0]/cluster/l2cache/mem_bus_cache_if[0]}  -recursive -reason EUR
coverage exclude -scope {/vortex_tb_top/dut/vortex/g_clusters[1]/cluster/l2cache/core_bus_cache_if[0]} -recursive -reason EUR
coverage exclude -scope {/vortex_tb_top/dut/vortex/g_clusters[1]/cluster/l2cache/mem_bus_cache_if[0]}  -recursive -reason EUR

# --- ECFG: TOTAL_CORES=4 (>1) -> global-barrier condition is REACHABLE, NOT excluded ---

# --- EUR: icache is WRITE_ENABLE(0) -> write-data payload structurally dead (OBS-033) ---
coverage exclude -scope {/vortex_tb_top/dut/vortex/g_clusters[0]/cluster/g_sockets[0]/socket/icache} -recursive -togglenode {req_data.data} -reason EUR
coverage exclude -scope {/vortex_tb_top/dut/vortex/g_clusters[0]/cluster/g_sockets[0]/socket/icache} -recursive -togglenode {req_data.byteen} -reason EUR
coverage exclude -scope {/vortex_tb_top/dut/vortex/g_clusters[0]/cluster/g_sockets[0]/socket/icache} -recursive -togglenode {per_bank_mem_req_data} -reason EUR
coverage exclude -scope {/vortex_tb_top/dut/vortex/g_clusters[0]/cluster/g_sockets[0]/socket/icache} -recursive -togglenode {per_bank_mem_req_byteen} -reason EUR
coverage exclude -scope {/vortex_tb_top/dut/vortex/g_clusters[0]/cluster/g_sockets[0]/socket/icache} -recursive -togglenode {mem_req_byteen} -reason EUR
coverage exclude -scope {/vortex_tb_top/dut/vortex/g_clusters[1]/cluster/g_sockets[0]/socket/icache} -recursive -togglenode {req_data.data} -reason EUR
coverage exclude -scope {/vortex_tb_top/dut/vortex/g_clusters[1]/cluster/g_sockets[0]/socket/icache} -recursive -togglenode {req_data.byteen} -reason EUR
coverage exclude -scope {/vortex_tb_top/dut/vortex/g_clusters[1]/cluster/g_sockets[0]/socket/icache} -recursive -togglenode {per_bank_mem_req_data} -reason EUR
coverage exclude -scope {/vortex_tb_top/dut/vortex/g_clusters[1]/cluster/g_sockets[0]/socket/icache} -recursive -togglenode {per_bank_mem_req_byteen} -reason EUR
coverage exclude -scope {/vortex_tb_top/dut/vortex/g_clusters[1]/cluster/g_sockets[0]/socket/icache} -recursive -togglenode {mem_req_byteen} -reason EUR

# --- EUR: uuid g_wid bits above the topology bound (OBS-034) ---
# NW_BITS=2 TOTAL_CORES=4 -> max g_wid=15 -> needs 4 bits
coverage exclude -scope {/vortex_tb_top/dut/vortex} -recursive -togglenode {uuid[43:36]} -reason EUR

# --- EUR: structural AXI cover-directives (restricted master; mirror of 148ff78) ---
coverage exclude -srcfile /home/samuel_ubuntu22/Vortex_UVM_GP/vortex_uvm_env/tb/vortex_axi_if.sv -linerange 755 -reason EUR ;# aw_burst_incr  (awburst hardwired FIXED)
coverage exclude -srcfile /home/samuel_ubuntu22/Vortex_UVM_GP/vortex_uvm_env/tb/vortex_axi_if.sv -linerange 757 -reason EUR ;# aw_burst_wrap  (awburst hardwired FIXED)
coverage exclude -srcfile /home/samuel_ubuntu22/Vortex_UVM_GP/vortex_uvm_env/tb/vortex_axi_if.sv -linerange 779 -reason EUR ;# awlen_2to4     (awlen hardwired 0)
coverage exclude -srcfile /home/samuel_ubuntu22/Vortex_UVM_GP/vortex_uvm_env/tb/vortex_axi_if.sv -linerange 781 -reason EUR ;# awlen_5to16    (awlen hardwired 0)
coverage exclude -srcfile /home/samuel_ubuntu22/Vortex_UVM_GP/vortex_uvm_env/tb/vortex_axi_if.sv -linerange 783 -reason EUR ;# awlen_17to64   (awlen hardwired 0)
coverage exclude -srcfile /home/samuel_ubuntu22/Vortex_UVM_GP/vortex_uvm_env/tb/vortex_axi_if.sv -linerange 785 -reason EUR ;# awlen_65to255  (awlen hardwired 0)
coverage exclude -srcfile /home/samuel_ubuntu22/Vortex_UVM_GP/vortex_uvm_env/tb/vortex_axi_if.sv -linerange 789 -reason EUR ;# concurrent_aw_ar (read XOR write per port)
coverage exclude -srcfile /home/samuel_ubuntu22/Vortex_UVM_GP/vortex_uvm_env/tb/vortex_axi_if.sv -linerange 763 -reason EUR ;# bresp_slverr   (slave OKAY-only)
coverage exclude -srcfile /home/samuel_ubuntu22/Vortex_UVM_GP/vortex_uvm_env/tb/vortex_axi_if.sv -linerange 765 -reason EUR ;# bresp_decerr   (slave OKAY-only)
coverage exclude -srcfile /home/samuel_ubuntu22/Vortex_UVM_GP/vortex_uvm_env/tb/vortex_axi_if.sv -linerange 771 -reason EUR ;# rresp_slverr   (slave OKAY-only)
coverage exclude -srcfile /home/samuel_ubuntu22/Vortex_UVM_GP/vortex_uvm_env/tb/vortex_axi_if.sv -linerange 773 -reason EUR ;# rresp_decerr   (slave OKAY-only)

# --- EUR: restricted-master AXI assertions (WRAP/INCR antecedent never holds) ---
coverage exclude -srcfile /home/samuel_ubuntu22/Vortex_UVM_GP/vortex_uvm_env/tb/vortex_axi_if.sv -linerange 586 -reason EUR ;# aw_wrap_len_legal
coverage exclude -srcfile /home/samuel_ubuntu22/Vortex_UVM_GP/vortex_uvm_env/tb/vortex_axi_if.sv -linerange 595 -reason EUR ;# ar_wrap_len_legal
coverage exclude -srcfile /home/samuel_ubuntu22/Vortex_UVM_GP/vortex_uvm_env/tb/vortex_axi_if.sv -linerange 605 -reason EUR ;# aw_4k_boundary (INCR)
coverage exclude -srcfile /home/samuel_ubuntu22/Vortex_UVM_GP/vortex_uvm_env/tb/vortex_axi_if.sv -linerange 615 -reason EUR ;# ar_4k_boundary (INCR)
# --- EUR: idle MEM-interface assertions (unused on an AXI build) ---
coverage exclude -srcfile /home/samuel_ubuntu22/Vortex_UVM_GP/vortex_uvm_env/tb/vortex_mem_if.sv -linerange 135 -reason EUR ;# req_valid_stable
coverage exclude -srcfile /home/samuel_ubuntu22/Vortex_UVM_GP/vortex_uvm_env/tb/vortex_mem_if.sv -linerange 138 -reason EUR ;# req_addr_stable
coverage exclude -srcfile /home/samuel_ubuntu22/Vortex_UVM_GP/vortex_uvm_env/tb/vortex_mem_if.sv -linerange 152 -reason EUR ;# rsp_valid_stable
coverage exclude -srcfile /home/samuel_ubuntu22/Vortex_UVM_GP/vortex_uvm_env/tb/vortex_mem_if.sv -linerange 155 -reason EUR ;# rsp_data_stable
# --- EUR: b_valid_stable unreachable — adapter hardwires m_axi_bready=1'b1 (VX_axi_adapter.sv:313) ---
coverage exclude -srcfile /home/samuel_ubuntu22/Vortex_UVM_GP/vortex_uvm_env/tb/vortex_axi_if.sv -linerange 374 -reason EUR ;# b_valid_stable (bready always 1)

# --- end generated exclusions (config 2CL/2C/4W/4T) ---
